//
// Generated file, do not edit! Created by opp_msgtool 6.2 from ClientRequestMessage.msg.
//

#ifndef __PROJECT_CLIENTREQUESTMESSAGE_M_H
#define __PROJECT_CLIENTREQUESTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace project {

class ClientRequestMessage;

}  // namespace project


namespace project {

/**
 * Class generated from <tt>ClientRequestMessage.msg:21</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message ClientRequestMessage
 * {
 *     int clientId;
 *     long requestId;
 * }
 * </pre>
 */
class ClientRequestMessage : public ::omnetpp::cMessage
{
  protected:
    int clientId = 0;
    long requestId = 0;

  private:
    void copy(const ClientRequestMessage& other);

  protected:
    bool operator==(const ClientRequestMessage&) = delete;

  public:
    ClientRequestMessage(const char *name=nullptr, short kind=0);
    ClientRequestMessage(const ClientRequestMessage& other);
    virtual ~ClientRequestMessage();
    ClientRequestMessage& operator=(const ClientRequestMessage& other);
    virtual ClientRequestMessage *dup() const override {return new ClientRequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getClientId() const;
    virtual void setClientId(int clientId);

    virtual long getRequestId() const;
    virtual void setRequestId(long requestId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClientRequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClientRequestMessage& obj) {obj.parsimUnpack(b);}


}  // namespace project


namespace omnetpp {

template<> inline project::ClientRequestMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<project::ClientRequestMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PROJECT_CLIENTREQUESTMESSAGE_M_H

