//
// Generated file, do not edit! Created by opp_msgtool 6.2 from EndFirstStageMessage.msg.
//

#ifndef __PROJECT_ENDFIRSTSTAGEMESSAGE_M_H
#define __PROJECT_ENDFIRSTSTAGEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace project {

class EndFirstStageMessage;

}  // namespace project


namespace project {

/**
 * Class generated from <tt>EndFirstStageMessage.msg:21</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet EndFirstStageMessage
 * {
 *     long requestId;
 * }
 * </pre>
 */
class EndFirstStageMessage : public ::omnetpp::cPacket
{
  protected:
    long requestId = 0;

  private:
    void copy(const EndFirstStageMessage& other);

  protected:
    bool operator==(const EndFirstStageMessage&) = delete;

  public:
    EndFirstStageMessage(const char *name=nullptr, short kind=0);
    EndFirstStageMessage(const EndFirstStageMessage& other);
    virtual ~EndFirstStageMessage();
    EndFirstStageMessage& operator=(const EndFirstStageMessage& other);
    virtual EndFirstStageMessage *dup() const override {return new EndFirstStageMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getRequestId() const;
    virtual void setRequestId(long requestId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EndFirstStageMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EndFirstStageMessage& obj) {obj.parsimUnpack(b);}


}  // namespace project


namespace omnetpp {

template<> inline project::EndFirstStageMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<project::EndFirstStageMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PROJECT_ENDFIRSTSTAGEMESSAGE_M_H

