//
// Generated file, do not edit! Created by opp_msgtool 6.2 from RequestMessage.msg.
//

#ifndef __PROJECT_REQUESTMESSAGE_M_H
#define __PROJECT_REQUESTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace project {

class RequestMessage;

}  // namespace project


namespace project {

/**
 * Class generated from <tt>RequestMessage.msg:21</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message RequestMessage
 * {
 *     long requestId;
 *     int threadId;
 * }
 * </pre>
 */
class RequestMessage : public ::omnetpp::cMessage
{
  protected:
    long requestId = 0;
    int threadId = 0;

  private:
    void copy(const RequestMessage& other);

  protected:
    bool operator==(const RequestMessage&) = delete;

  public:
    RequestMessage(const char *name=nullptr, short kind=0);
    RequestMessage(const RequestMessage& other);
    virtual ~RequestMessage();
    RequestMessage& operator=(const RequestMessage& other);
    virtual RequestMessage *dup() const override {return new RequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getRequestId() const;
    virtual void setRequestId(long requestId);

    virtual int getThreadId() const;
    virtual void setThreadId(int threadId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RequestMessage& obj) {obj.parsimUnpack(b);}


}  // namespace project


namespace omnetpp {

template<> inline project::RequestMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<project::RequestMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PROJECT_REQUESTMESSAGE_M_H

